### ISSUE TITLE
Trackmate extra won't run

### ISSUE THREAD

**Issue by MichaelSunJK** [tinevez/TrackMate-extras#7]
Dear Jean-Yves,

The trackmate extra stopped working for me. All the tools disappeared in trackmate. Even through I put the scripts in jar folder. I am using fiji on MacOS Catalina.
Thanks in advance!

Michael

**Comment by tinevez** [comment]
Hello Michael. Sorry for this.

Can you give me some more info? Where did you download the extra from? 
What version of TrackMate are you using?

**Comment by MichaelSunJK** [comment]
Dear Jean-Yves,
Thank you so much for your reply.
I downloaded track-mate extra from GitHub directly, which I assume is the newest version, then I uncompressed it and copy the whole folder (TrackMate-extras-master) into jars. My Fiji is version 2.1.0/1.53h. The previous 1.53 version also didn’t work.
Thanks again!
Michael



Le 19 févr. 2021 à 11:27, Jean-Yves Tinevez <notifications@github.com> a écrit :

﻿

Hello Michael. Sorry for this.

Can you give me some more info? Where did you download the extra from?
What version of TrackMate are you using?

**Comment by tinevez** [comment]
Ok. I would to know the TrackMate version too.
As for the extras, could you try this one  instead: 
https://maven.scijava.org/service/local/repositories/releases/content/org/scijava/TrackMate_extras/0.0.4/TrackMate_extras-0.0.4.jar

**Comment by MichaelSunJK** [comment]
The trackmate version is v6.0.1

On 19 Feb 2021, at 18:19, Jean-Yves Tinevez <notifications@github.com<mailto:notifications@github.com>> wrote:



Ok. I would to know the TrackMate version too.
As for the extras, could you try this one instead:
https://maven.scijava.org/service/local/repositories/releases/content/org/scijava/TrackMate_extras/0.0.4/TrackMate_extras-0.0.4.jar

**Comment by MichaelSunJK** [comment]
The TrackMate_extras-0.0.4.jar<https://maven.scijava.org/service/local/repositories/releases/content/org/scijava/TrackMate_extras/0.0.4/TrackMate_extras-0.0.4.jar> you sent me is working! Thanks!

On 19 Feb 2021, at 18:21, Sun Shoujie <shoujie.sun@epfl.ch<mailto:shoujie.sun@epfl.ch>> wrote:

The trackmate version is v6.0.1

On 19 Feb 2021, at 18:19, Jean-Yves Tinevez <notifications@github.com<mailto:notifications@github.com>> wrote:



Ok. I would to know the TrackMate version too.
As for the extras, could you try this one instead:
https://maven.scijava.org/service/local/repositories/releases/content/org/scijava/TrackMate_extras/0.0.4/TrackMate_extras-0.0.4.jar
